<?php
/**
 * Poll product renderer.
 * Outputs one product's image, description, and its 5-question
 * radio button table. Used by both poll-get.php and poll-post.php
 * so the 15-radio-button markup for each poll is generated by one
 * function instead of being typed out three times per page.
 *
 * @param array $product   One entry from $pollProducts (id, name, image, description)
 * @param array $questions The $pollQuestions array (key => statement)
 * @param array $scale     The $pollScale array (value => label), ordered strongly agree -> strongly disagree
 */
function render_poll_product($product, $questions, $scale) {
    // Basic error handling: skip cleanly instead of throwing
    // notices if a product is ever missing required fields.
    if (empty($product['id']) || empty($product['name'])) {
        echo '<p><em>A product in this poll is missing information and could not be displayed.</em></p>';
        return;
    }

    $id   = htmlspecialchars($product['id'], ENT_QUOTES, 'UTF-8');
    $name = htmlspecialchars($product['name'], ENT_QUOTES, 'UTF-8');
    $desc = htmlspecialchars(isset($product['description']) ? $product['description'] : '', ENT_QUOTES, 'UTF-8');
    $img  = htmlspecialchars(isset($product['image']) ? $product['image'] : '', ENT_QUOTES, 'UTF-8');
    ?>
    <fieldset class="poll-product">
        <legend><?php echo $name; ?></legend>
        <img src="<?php echo $img; ?>" alt="<?php echo $name; ?>" width="120" height="120" class="poll-product-image" />
        <p class="poll-product-description"><?php echo $desc; ?></p>

        <table>
            <tr>
                <th scope="col">Statement</th>
                <?php foreach ($scale as $scaleLabel): ?>
                    <th scope="col"><?php echo htmlspecialchars($scaleLabel, ENT_QUOTES, 'UTF-8'); ?></th>
                <?php endforeach; ?>
            </tr>
            <?php foreach ($questions as $qKey => $qText): ?>
            <tr>
                <td><?php echo htmlspecialchars($qText, ENT_QUOTES, 'UTF-8'); ?></td>
                <?php foreach ($scale as $scaleValue => $scaleLabel):
                    $fieldName = $id . '_' . $qKey;
                    $inputId   = $fieldName . '_' . $scaleValue;
                    ?>
                <td class="poll-radio-cell">
                    <input type="radio"
                           id="<?php echo htmlspecialchars($inputId, ENT_QUOTES, 'UTF-8'); ?>"
                           name="<?php echo htmlspecialchars($fieldName, ENT_QUOTES, 'UTF-8'); ?>"
                           value="<?php echo htmlspecialchars($scaleValue, ENT_QUOTES, 'UTF-8'); ?>"
                           required="required" />
                    <label for="<?php echo htmlspecialchars($inputId, ENT_QUOTES, 'UTF-8'); ?>" class="visually-hidden">
                        <?php echo htmlspecialchars($scaleLabel, ENT_QUOTES, 'UTF-8'); ?>
                    </label>
                </td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </table>
    </fieldset>
    <?php
}
?>
